[package]
name = "b2441_rust"
version = "0.1.0"
authors = ["d2h10s <ecanus9@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
